[package]
name = "rust_for_all"
version = "0.1.0"
authors = ["fqliao <fqliao@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.60"

